export interface StationsApi {
  stations: {
    info: {
      name: string;
      code: string;
      stopTrains: number[];
    };
  }[];
}

// https://www.train-guide.westjr.co.jp/api/v3/manyomahoroba_st.json
//
// Example:
// const result = {
//   stations: [
//     {
//       info: {
//         name: '奈良',
//         code: '0588',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: [
//           {
//             name: '奈良線',
//             type: 0,
//             code: 'nara_nolink',
//             link: null,
//             linkCode: null,
//             note: null,
//             substitute: false,
//           },
//           {
//             name: '大和路線',
//             type: 0,
//             code: 'yamatoji',
//             link: 'yamatoji',
//             linkCode: '3020',
//             note: null,
//             substitute: false,
//           },
//           {
//             name: '西日本ジェイアールバス',
//             type: 5,
//             code: 'jrwbus',
//             link: null,
//             linkCode: null,
//             note: null,
//             substitute: false,
//           },
//           {
//             name: '奈良交通',
//             type: 6,
//             code: 'narakotsu',
//             link: null,
//             linkCode: null,
//             note: null,
//             substitute: false,
//           },
//         ],
//         colorCode: 'kku',
//         transferIcons: [0, 2],
//         notDisplayType: 4,
//         notDisplayNotices: ['この区間は', '一部列車が表', '示されません'],
//         end: true,
//       },
//       design: {
//         mark: 'downonly',
//         upside: [
//           {
//             type: 99,
//             side: null,
//             linkLine: null,
//             linkStationCode: null,
//             colorCode: null,
//           },
//         ],
//         downside: null,
//       },
//     },
//     {
//       info: {
//         name: '京終',
//         code: '0589',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '帯解',
//         code: '0590',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '櫟本',
//         code: '0591',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '天理',
//         code: '0592',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: [
//           {
//             name: '近鉄電車',
//             type: 2,
//             code: 'kintetsurailway_tenri1',
//             link:
//               'https://tid.kintetsu.co.jp/LocationWeb/trainlocationinfoweb05.html?eki=71',
//             linkCode: '0592',
//             note: null,
//             substitute: false,
//           },
//           {
//             name: '大阪空港交通',
//             type: 6,
//             code: 'osakaairportbus',
//             link: null,
//             linkCode: null,
//             note: null,
//             substitute: false,
//           },
//           {
//             name: '奈良交通',
//             type: 6,
//             code: 'narakotsu',
//             link: null,
//             linkCode: null,
//             note: null,
//             substitute: false,
//           },
//         ],
//         colorCode: 'kku',
//         transferIcons: [0, 2],
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '長柄',
//         code: '0593',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: 5,
//         notDisplayNotices: ['この区間は実', '際の走行位置', 'と異なります'],
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '柳本',
//         code: '0594',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '巻向',
//         code: '0595',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: 5,
//         notDisplayNotices: ['この区間は実', '際の走行位置', 'と異なります'],
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '三輪',
//         code: '0596',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '桜井',
//         code: '0597',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: [
//           {
//             name: '近鉄電車',
//             type: 2,
//             code: 'kintetsurailway_osaka1',
//             link:
//               'https://tid.kintetsu.co.jp/LocationWeb/trainlocationinfoweb07.html?eki=121',
//             linkCode: '0597',
//             note: null,
//             substitute: false,
//           },
//           {
//             name: '奈良交通',
//             type: 6,
//             code: 'narakotsu',
//             link: null,
//             linkCode: null,
//             note: null,
//             substitute: false,
//           },
//         ],
//         colorCode: 'kku',
//         transferIcons: [0, 2],
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '香久山',
//         code: '0598',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: 5,
//         notDisplayNotices: ['この区間は実', '際の走行位置', 'と異なります'],
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '畝傍',
//         code: '0599',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '金橋',
//         code: '0600',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: null,
//         colorCode: 'kku',
//         transferIcons: null,
//         notDisplayType: 5,
//         notDisplayNotices: ['この区間は実', '際の走行位置', 'と異なります'],
//         end: false,
//       },
//       design: { mark: null, upside: null, downside: null },
//     },
//     {
//       info: {
//         name: '高田',
//         code: '0601',
//         stopTrains: [2],
//         typeNotice: null,
//         transfer: [
//           {
//             name: '和歌山線',
//             type: 0,
//             code: 'wakayama2',
//             link: 'wakayama2',
//             linkCode: '0601',
//             note: '王寺 ～ 五条',
//             substitute: false,
//           },
//           {
//             name: '奈良交通',
//             type: 6,
//             code: 'narakotsu',
//             link: null,
//             linkCode: null,
//             note: null,
//             substitute: false,
//           },
//         ],
//         colorCode: 'kku',
//         transferIcons: [0, 2],
//         notDisplayType: null,
//         notDisplayNotices: null,
//         end: false,
//       },
//       design: {
//         mark: 'uponly',
//         upside: null,
//         downside: [
//           {
//             type: 98,
//             side: null,
//             linkLine: 'wakayama2',
//             linkStationCode: '0601',
//             colorCode: 'kkt',
//           },
//         ],
//       },
//     },
//   ],
// };
